export * from './HomePage';
export * from './AboutPage';
export * from './CellPhonesPage';
export * from './CellPhonePage';
export * from './BrandsPage';
export * from './CategoriesPage';
export * from './LoginPage';
export * from './RegisterPage';
export * from './OrdersUserPage';
export * from './CheckoutPage';
export * from './ThankyouPage';
export * from './OrderUserPage';
export * from './dashboard/DashboardProductsPage'
export * from './dashboard/DashboardCategoriesPage'
export * from './dashboard/DashboardBrandsPage'